version: '3.9'

services:
    web:
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app

    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app

    mysql:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'yewacA1k2U6K'
            MYSQL_USER: 'netvolution_lmb'
            MYSQL_PASSWORD: 'a6tz6uB8CNsn'
            MYSQL_DATABASE: 'netvolution_lmb'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3308:3306

    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        environment:
            - PMA_ARBITRARY=1
        ports:
            - "8889:80"

    adminer:
        image: adminer:latest
        restart: always
        ports:
            - "8080:8080"

volumes:
    mysqldata: {}
